(module tests racket
  (provide runtests)
  (require "../s/test-driver.ss")
  (define (runtests)
    (test-cases "fixnum-only operations"

      ;; fixnum? tests (Step 1)
      (test-case (fixnum? 0) "#t")
      (test-case (fixnum? 5) "#t")
      (test-case (fixnum? -42) "#t")
      (test-case (fixnum? #t) "#f")
      (test-case (fixnum? #f) "#f")
      (test-case (fixnum? #\a) "#f")
      (test-case (fixnum? '()) "#f")
      (test-case (fixnum? (cons 1 2)) "#f")
      (test-case (fixnum? (make-ratnum 1 2)) "#f")

      ;; fx= tests (Step 2 - fixnum-only equality, no type checking)
      (test-case (fx= 0 0) "#t")
      (test-case (fx= 5 5) "#t")
      (test-case (fx= -42 -42) "#t")
      (test-case (fx= 0 1) "#f")
      (test-case (fx= 5 6) "#f")
      (test-case (fx= -1 1) "#f")
      (test-case (fx= 100 100) "#t")
      (test-case (fx= -100 -100) "#t")

      ;; mml added these just for debugging
      (test-case (fx= 2 3) "#f")
      (test-case (= 2 3) "#f")

      ;; fx< tests (Step 3 - fixnum-only less-than, no type checking)
      (test-case (fx< 0 1) "#t")
      (test-case (fx< -5 5) "#t")
      (test-case (fx< -10 -5) "#t")
      (test-case (fx< 1 0) "#f")
      (test-case (fx< 5 -5) "#f")
      (test-case (fx< 0 0) "#f")
      (test-case (fx< 42 42) "#f")
      (test-case (fx< -100 100) "#t")

      ;; fx> tests (Step 4 - fixnum-only greater-than, no type checking)
      (test-case (fx> 1 0) "#t")
      (test-case (fx> 5 -5) "#t")
      (test-case (fx> -5 -10) "#t")
      (test-case (fx> 0 1) "#f")
      (test-case (fx> -5 5) "#f")
      (test-case (fx> 0 0) "#f")
      (test-case (fx> 42 42) "#f")
      (test-case (fx> 100 -100) "#t")

      ;; fx<= tests (Step 5 - fixnum-only less-than-or-equal, no type checking)
      (test-case (fx<= 0 0) "#t")
      (test-case (fx<= 0 1) "#t")
      (test-case (fx<= -5 5) "#t")
      (test-case (fx<= -10 -5) "#t")
      (test-case (fx<= 5 5) "#t")
      (test-case (fx<= 1 0) "#f")
      (test-case (fx<= 5 -5) "#f")
      (test-case (fx<= -100 100) "#t")

      ;; fx>= tests (Step 6 - fixnum-only greater-than-or-equal, no type checking)
      (test-case (fx>= 0 0) "#t")
      (test-case (fx>= 1 0) "#t")
      (test-case (fx>= 5 -5) "#t")
      (test-case (fx>= -5 -10) "#t")
      (test-case (fx>= 5 5) "#t")
      (test-case (fx>= 0 1) "#f")
      (test-case (fx>= -5 5) "#f")
      (test-case (fx>= 100 -100) "#t")

      )))
